spring.datasource.url=jdbc:postgresql://localhost:5432/payroll_db
spring.datasource.username=coloque_seu_usuario
spring.datasource.password=coloque_sua_senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
